jobs: 50
latency-wait: 60
max-jobs-per-second: 50
executor: slurm

# use-conda: true
default-resources:
#  - disk_mb=500000
#  - mem_mb=16096
  runtime: 5760
  slurm_partition: gpu-core
  slurm_account: sarthy_lab
  cpus_per_task: 32
  mem_mb_per_cpu: 15000
